#import "../../style.typ": hero

= Tungsten

== \

#hero[Spark was spending half its time \ on *GC* and *boxing*. \ Tungsten fixed both.]

== The problem Tungsten solves

Before Spark 1.5, Spark stored data as JVM objects:

- Every `Row` was a heap-allocated object with header overhead (16 bytes minimum)
- Column values were boxed: an `Integer` wraps an `int`, adding 16 bytes of overhead
- The garbage collector had to scan millions of short-lived objects between stages
- GC pauses of 10–30 seconds were common on large shuffles

Tungsten is Spark's answer: *manage memory manually*, store data in a compact binary format, generate native JVM bytecode instead of interpreting plans.

== Off-heap memory management

Tungsten uses `sun.misc.Unsafe` to allocate memory *outside the JVM heap*:

- The GC never sees this memory — no GC pressure, no GC pauses
- Data is stored in a *compact binary row format* (UnsafeRow)
- Rows can be compared and sorted without deserialization
- Memory can be spilled to disk without serialization overhead

`UnsafeRow` layout: a fixed-length null bitmap + fixed-length values section + variable-length data appended at the end. The whole row is contiguous bytes.

== Whole-Stage Code Generation

For each query, Tungsten generates a *single Java class* that implements the entire pipeline.

The generated class:
- Iterates over input rows in a tight loop
- Has all operators inlined (no virtual calls)
- Uses primitive types directly (no boxing)
- Is compiled by the JVM JIT into native machine code

The compilation happens at query planning time on the driver. The generated bytecode is sent to executors as part of the task.

You can see the generated code with `df.queryExecution.debug.codegen()`.

== What gets code-generated (and what doesn't)

Operators inside a `*(N)` block in the plan are fused into one generated stage:
- Filter, Project, HashAggregate, BroadcastHashJoin, Sort

Operators that *break* code generation:
- `Exchange` (shuffle — data must leave the process)
- `HashAggregate` (the partial agg is code-gen'd; the merge is a separate stage)
- Python UDFs — they cross the JVM/Python boundary, breaking the generated loop

*Python UDFs are the single biggest Tungsten performance killer.* They force row-by-row serialization to a Python process and back, bypassing all code generation.

== Impact

Benchmarks comparing Spark before and after Tungsten show 5–10× speedups on aggregation-heavy workloads and 2–3× on join-heavy ones.

The gains come from eliminating:
- Deserialization to `Row` objects (use `UnsafeRow` directly)
- GC pressure on intermediate results
- Virtual dispatch overhead in the Volcano iterator chain
- Redundant serialization across operators in the same stage
